### PR TITLE
Fix bash script bug and Add new Language Selection Feature

### LINKED ISSUE #98: 编写统一安装的 shell 和 PowerShell 脚本
现有的安装方式比较麻烦，用户需要手动根据操作系统和CPU类型来区分下载链接。该 challenge 邀请贡献者参与编写 ：

1. shell 脚本
2. PowerShell 脚本

`chsrc` 项目支持一定程度的AI编写，但如果主要内容均由AI完成，需要将文件头作者填写为AI产品名。欢迎 `shell` 脚本初学者 和 `PowerShell` 初学者优先贡献

<br>

# Shell 脚本 TODO

- [x] 基本框架
- [x] 支持 macOS 用户 和 Linux 用户
- [x] 使用标准默认安装目录
- [x] 支持自定义安装目录
- [x] 支持英语输出
- [ ] BSD 用户也可使用该脚本，但并不是下载，而是调用 `clang`/`gcc`/`gmake` 自己编译
- [ ] 其它POSIX平台，调用 `clang`/`gcc`/`make` 自己编译 

<br>

# PowerShell 脚本 TODO

- [x] 基本框架
- [x] 确定一个标准的可以执行exe的安装目录 → 不能执行，但标准：`~/Downloads`
- [x] 支持自定义安装目录

<br>

### PR DESCRIPTION
**Pull request by LouieWickDing**
## Overview of Changes
1. Add new feature to install.sh: specify the language, use `-l zh` or `-l en` to select.
2. Fix the architect selection bugs: now can identify not only `aarch64` but also `arm64` arch.
3. Fix the empty directory bug: if your specified dir not exist, it will create one.
4. Add readme.txt: describe the usage of script.

## Related Issues
Fixed #98 

## Type of Change
- [X] Bug fix
- [X] New feature
- [X] Documentation update
- [X] Code refactoring

## Impact
Fix the install bugs, also add new language seleted feature, and make scripts more readable and usable.

## Pretending Test
Use  install.sh to install any version on any architect and os, test any couples of flags.

### CODE REVIEW

**Comment by ccmywish** [comment]
@1328032567 

Your code is very helpful and meticulous. Thank you! 👍

**Comment by 1328032567** [comment]
> @1328032567
> 
> Your code is very helpful and meticulous. Thank you! 👍

Thanks for your praise, I'm very grateful and delighted.
I consider to use `getopt` func to instead of `getopts` so that the script can parser `long option` like this `--help`. However, the concrete implement of `getopt` is not always the same on different OS, so I give up. To fix and also implement this file, I referred to the content of classical project build-scripts.
Btw, I'd also like to implement the **powershell version**, but I'm new in posh, so I'd also like to refer the context from other projects.

**Comment by ccmywish** [comment]
I already added a simple PowerShell version, very simple, you can modify and improve it as you like. Go for it~

**Comment by 1328032567** [comment]
> I already added a simple PowerShell version, very simple, you can modify and improve it as you like. Go for it~

Gosh! U are so considerate, I'll hurry up. Thank you for your replying.

**Pull request merged**
