### PR TITLE
chore(license): update spdx id in docs

### PR DESCRIPTION
**Pull request by chenrui333**
followup #26 

---

missed it in the first place

### CODE REVIEW

**Comment by ccmywish** [comment]
Thank you Rui, 🤝

I'm not very familiar with license issues, so I need to consult you about it. 

I'm not sure if it's "dual license" as people understand. And I admit the sentence this PR focused on is kind of misleading.

<br>

This project includes a file called `./include/xy.h`, which is a common C lib file I write to help to make program `chsrc.c` and `chsrc.h` easily. I want to make the `xy.h` more permissive, so I can use it in other non-GPL-3.0-or-later projects

**I want to make `chsrc` only `GPL-3.0-or-later`.**  and  **`chsrc` is based on the MIT licensed `./include/xy.h`**

So, according to my idea above,  is my situation called `dual licensed`?  Does the two licenses conflict?

**Comment by chenrui333** [comment]
> I'm not sure if it's "dual license" as people understand. And I admit the sentence this PR focused on is kind of misleading.

it is not dual license, so that is reason why it should use `and` rather than `or`

technically, I would also split the license file into two and just contain the standard body from the license templates (it would also help github, but not fully)

**Comment by ccmywish** [comment]
Well and clearly explained!

**Comment by chenrui333** [comment]
THanks @ccmywish! 🙌 

you can see now, it looks a bit better :) 

image

**Pull request merged**
