### PR TITLE
[UPDATE] Add new section to PR template

### PR DESCRIPTION
**Pull request by wickdynex**
### Description

Update PR default template content, add new section and examples also related issue to this template.

### Additional Notes

If there's some mistake I made, plz comment, and I'll fix it and polish until is ready to be merged. Thanks😊.

### CODE REVIEW

**Comment by ccmywish** [comment]
Wow, such a detailed PR, thank you! 👍

---

1. In your example `变更内容` and `描述` are too alike
2. `相关问题` should be put into `描述`
3. `备注` and `风险与注意事项` can merge
4. We must have a `方案` and `实现` section, this is very important
5. `测试说明` should be the last section, simply renamed as `测试` 
6. There is no need for a `总结`

---

Please change it to this, and merge your content according to it.

```markdown

### 描述

（1）问题的背景
（2）相关issue
（3）这个PR做了什么

### 方案

...

### 实现

...

### 注意

...

### 测试

```

**Comment by wickdynex** [comment]
Hi @ccmywish ,
I've polished it and modified as your comment, how about now?😊

**Comment by ccmywish** [comment]
Now new pull requests can have a solid base, thank you very much! 👍

**Comment by wickdynex** [comment]
> Now new pull requests can have a solid base, thank you very much! 👍

Welcome🤗

**Pull request merged**
